extension L10n {
    static let german: [String: String] = [
        "Не удалось прочитать хранилище. Данные не изменены.": "Der Tresor konnte nicht gelesen werden. Deine Daten wurden nicht geändert.",
        "Хранилище содержит повреждённые данные. Оно не будет перезаписано.": "Der Tresor enthält beschädigte Daten. Er wird nicht überschrieben.",
        "NotchOTP — аккаунты двухфакторной аутентификации": "NotchOTP — Konten mit Zwei-Faktor-Authentifizierung",
        "Проверьте секретный ключ: нужны буквы A–Z и цифры 2–7 в формате Base32.": "Prüfe den geheimen Schlüssel: Verwende A–Z und 2–7 im Base32-Format.",
        "Укажите название аккаунта (до 200 символов) и сервиса (до 100).": "Gib einen Kontonamen (bis zu 200 Zeichen) und einen Dienstnamen (bis zu 100) ein.",
        "Секретный ключ пустой или слишком длинный.": "Der geheime Schlüssel ist leer oder zu lang.",
        "Поддерживаются только SHA1, SHA256 и SHA512.": "Nur SHA1, SHA256 und SHA512 werden unterstützt.",
        "Поддерживаются 6 или 8 цифр и период от 1 до 3600 секунд.": "Verwende 6 oder 8 Ziffern und ein Intervall von 1 bis 3600 Sekunden.",
        "Нужна ссылка otpauth://totp/… из настройки двухфакторной аутентификации.": "Verwende einen otpauth://totp/…-Link aus den Einstellungen der Zwei-Faktor-Authentifizierung.",
        "Этот QR-код не является TOTP. HOTP и пакетный перенос Google пока не поддерживаются.": "Dieser QR-Code ist kein TOTP-Code. HOTP und die Google-Massenübertragung werden noch nicht unterstützt.",
        "В ссылке повторяются параметры. Получите новый QR-код у сервиса.": "Der Link enthält doppelte Parameter. Fordere beim Dienst einen neuen QR-Code an.",
        "В QR-коде отсутствует секретный ключ.": "Der QR-Code enthält keinen geheimen Schlüssel.",
        "Названия сервиса в QR-коде не совпадают. Проверьте источник.": "Die Dienstnamen im QR-Code stimmen nicht überein. Prüfe die Quelle.",
        "Некорректное число цифр или период в QR-коде.": "Der QR-Code enthält eine ungültige Ziffernanzahl oder ein ungültiges Intervall.",
        "Нажмите сочетание…": "Tastenkürzel drücken…",
        "Это деморежим. Перезапустите приложение, чтобы добавить свой аккаунт.": "Dies ist der Demomodus. Starte die App neu, um dein eigenes Konto hinzuzufügen.",
        "Сначала откройте доступ к связке ключей.": "Entsperre zuerst den Schlüsselbund.",
        "Этот аккаунт уже добавлен.": "Dieses Konto wurde bereits hinzugefügt.",
        "Ключ исчезнет из NotchOTP. Убедитесь, что у вас есть другой способ входа в этот аккаунт.": "Der Schlüssel wird aus NotchOTP entfernt. Stelle sicher, dass du dich auf anderem Weg bei diesem Konto anmelden kannst.",
        "Отмена": "Abbrechen",
        "Удалить": "Löschen",
        "Не удалось скопировать код. Попробуйте ещё раз.": "Der Code konnte nicht kopiert werden. Versuche es erneut.",
        "Не удалось зарегистрировать сочетание. Выберите другое в настройках; панель доступна через значок ключа в строке меню.": "Das Tastenkürzel konnte nicht registriert werden. Wähle ein anderes in den Einstellungen. Über das Schlüsselsymbol in der Menüleiste kannst du das Panel öffnen.",
        "Аккаунты и настройки…": "Konten und Einstellungen…",
        "Завершить NotchOTP": "NotchOTP beenden",
        "Правка": "Bearbeiten",
        "Отменить": "Widerrufen",
        "Вырезать": "Ausschneiden",
        "Копировать": "Kopieren",
        "Вставить": "Einsetzen",
        "Выбрать всё": "Alles auswählen",
        "Это сочетание занято. Попробуйте другое; прежнее сочетание продолжает работать.": "Dieses Tastenkürzel ist bereits belegt. Versuche ein anderes. Dein bisheriges Tastenkürzel funktioniert weiterhin.",
        "Выберите изображение с QR-кодом": "Bild mit QR-Code auswählen",
        "Не удалось открыть изображение. Выберите PNG или JPEG с QR-кодом.": "Das Bild konnte nicht geöffnet werden. Wähle eine PNG- oder JPEG-Datei mit einem QR-Code.",
        "На изображении несколько аккаунтов. Обрежьте его до одного QR-кода.": "Das Bild enthält mehrere Konten. Schneide es auf einen einzigen QR-Code zu.",
        "QR-код TOTP не найден. Выберите более чёткое изображение кода из настроек безопасности сервиса. Пакетный перенос Google не поддерживается.": "Kein TOTP-QR-Code gefunden. Wähle ein schärferes Bild aus den Sicherheitseinstellungen des Dienstes. Die Google-Massenübertragung wird nicht unterstützt.",
        "Ваши коды. Под рукой.": "Deine Codes. Immer griffbereit.",
        "Вызовите панель, выберите аккаунт и нажмите Enter.": "Öffne das Panel, wähle ein Konto und drücke Enter.",
        "Деморежим · показаны тестовые аккаунты": "Demomodus · Beispielkonten",
        "Аккаунты": "Konten",
        "Читаем…": "Wird gelesen…",
        "QR из файла": "QR aus Datei",
        "Добавить": "Hinzufügen",
        "Глобальное сочетание": "Globales Tastenkürzel",
        "Нажмите справа, затем введите новое сочетание.": "Klicke rechts und drücke dann ein neues Tastenkürzel.",
        "Используйте Control, Option или Command вместе с клавишей. Escape — отмена.": "Verwende Control, Option oder Command mit einer Taste. Escape bricht ab.",
        "Аккаунт": "Konto",
        "Текст": "Tippen",
        "Поиск": "Suchen",
        "Закрыть": "Schließen",
        "Показать панель": "Panel anzeigen",
        "Ключи хранятся в связке ключей этого Mac. Всё работает локально.": "Die Schlüssel liegen im Schlüsselbund dieses Mac. Alles läuft lokal.",
        "Добавить аккаунт?": "Konto hinzufügen?",
        "Не удалось выполнить действие": "Die Aktion konnte nicht ausgeführt werden",
        "Понятно": "OK",
        "Откройте доступ к связке ключей": "Schlüsselbund entsperren",
        "Повторить": "Erneut versuchen",
        "Добавьте первый аккаунт": "Füge dein erstes Konto hinzu",
        "Выберите QR-код из настроек двухфакторной\nаутентификации или введите секретный ключ.": "Wähle einen QR-Code aus den Einstellungen der Zwei-Faktor-\nAuthentifizierung oder gib einen geheimen Schlüssel ein.",
        "Показать": "Anzeigen",
        "Удалить аккаунт": "Konto löschen",
        "Новый аккаунт": "Neues Konto",
        "Способ": "Methode",
        "Секретный ключ": "Geheimer Schlüssel",
        "Ссылка otpauth": "otpauth-Link",
        "Сервис": "Dienst",
        "Например, GitHub": "Zum Beispiel GitHub",
        "Например, work или email": "Zum Beispiel Arbeit oder E-Mail",
        "Секретный ключ Base32": "Geheimer Base32-Schlüssel",
        "Ключ из настроек двухфакторной аутентификации": "Schlüssel aus den Einstellungen der Zwei-Faktor-Authentifizierung",
        "Дополнительные параметры": "Erweiterte Einstellungen",
        "Алгоритм": "Algorithmus",
        "Цифры": "Ziffern",
        "Период, секунд": "Intervall in Sekunden",
        "Ссылка из настроек сервиса": "Link aus den Einstellungen des Dienstes",
        "Ключ останется в связке ключей этого Mac.": "Der Schlüssel bleibt im Schlüsselbund dieses Mac.",
        "Период должен быть целым числом секунд.": "Das Intervall muss eine ganze Zahl von Sekunden sein.",
        "Некорректные параметры кода или системное время.": "Ungültige Codeparameter oder Systemzeit.",
        "Этот алгоритм не поддерживается. Используйте SHA1, SHA256 или SHA512.": "Dieser Algorithmus wird nicht unterstützt. Verwende SHA1, SHA256 oder SHA512.",
        "Связка ключей закрыта": "Schlüsselbund gesperrt",
        "Открыть настройки": "Einstellungen öffnen",
        "Настроить NotchOTP": "NotchOTP einrichten",
        "Скопировано": "Kopiert",
        "Enter — скопировать · Tab — следующий · Начните печатать для поиска": "Enter: kopieren · Tab: weiter · Tippen zum Suchen",
        "Найти аккаунт…": "Konto suchen…",
        "Ничего не найдено": "Keine Konten gefunden",
        "↑↓ Выбрать": "↑↓ Auswählen",
        "↵ Копировать": "↵ Kopieren",
        "Язык": "Sprache",
        "Как в macOS": "Wie macOS",
        "Применяется сразу, без перезапуска.": "Änderungen werden sofort wirksam.",
        "Удалить %@?": "%@ löschen?",
        "Удалить %@": "%@ löschen",
        "Показать код   %@": "Code anzeigen   %@",
        "%d цифр · %d сек": "%d Ziffern · %d Sek.",
        "%d цифр · %d сек · %@": "%d Ziffern · %d Sek. · %@",
        "Осталось %d секунд": "Noch %d Sekunden",
        "Ошибка %d": "Fehler %d",
        "Связка ключей недоступна: %@. Разблокируйте её и попробуйте снова.": "Schlüsselbund nicht verfügbar: %@. Entsperre ihn und versuche es erneut.",
    ]
}
