extension L10n {
    static let french: [String: String] = [
        "Не удалось прочитать хранилище. Данные не изменены.": "Impossible de lire le coffre. Vos données n’ont pas été modifiées.",
        "Хранилище содержит повреждённые данные. Оно не будет перезаписано.": "Le coffre contient des données endommagées. Il ne sera pas écrasé.",
        "NotchOTP — аккаунты двухфакторной аутентификации": "NotchOTP — comptes avec authentification à deux facteurs",
        "Проверьте секретный ключ: нужны буквы A–Z и цифры 2–7 в формате Base32.": "Vérifiez la clé secrète : utilisez les lettres A–Z et les chiffres 2–7 au format Base32.",
        "Укажите название аккаунта (до 200 символов) и сервиса (до 100).": "Saisissez un nom de compte (200 caractères maximum) et de service (100 maximum).",
        "Секретный ключ пустой или слишком длинный.": "La clé secrète est vide ou trop longue.",
        "Поддерживаются только SHA1, SHA256 и SHA512.": "Seuls SHA1, SHA256 et SHA512 sont pris en charge.",
        "Поддерживаются 6 или 8 цифр и период от 1 до 3600 секунд.": "Utilisez 6 ou 8 chiffres et une période de 1 à 3600 secondes.",
        "Нужна ссылка otpauth://totp/… из настройки двухфакторной аутентификации.": "Utilisez un lien otpauth://totp/… issu des réglages d’authentification à deux facteurs.",
        "Этот QR-код не является TOTP. HOTP и пакетный перенос Google пока не поддерживаются.": "Ce code QR n’est pas de type TOTP. HOTP et le transfert groupé de Google ne sont pas encore pris en charge.",
        "В ссылке повторяются параметры. Получите новый QR-код у сервиса.": "Le lien contient des paramètres en double. Obtenez un nouveau code QR auprès du service.",
        "В QR-коде отсутствует секретный ключ.": "Le code QR ne contient pas de clé secrète.",
        "Названия сервиса в QR-коде не совпадают. Проверьте источник.": "Les noms de service dans le code QR ne correspondent pas. Vérifiez sa source.",
        "Некорректное число цифр или период в QR-коде.": "Le nombre de chiffres ou la période dans le code QR est incorrect.",
        "Нажмите сочетание…": "Appuyez sur le raccourci…",
        "Это деморежим. Перезапустите приложение, чтобы добавить свой аккаунт.": "Ceci est le mode démo. Relancez l’app pour ajouter votre propre compte.",
        "Сначала откройте доступ к связке ключей.": "Déverrouillez d’abord le trousseau.",
        "Этот аккаунт уже добавлен.": "Ce compte a déjà été ajouté.",
        "Ключ исчезнет из NotchOTP. Убедитесь, что у вас есть другой способ входа в этот аккаунт.": "La clé sera supprimée de NotchOTP. Assurez-vous de disposer d’un autre moyen de vous connecter à ce compte.",
        "Отмена": "Annuler",
        "Удалить": "Supprimer",
        "Не удалось скопировать код. Попробуйте ещё раз.": "Impossible de copier le code. Réessayez.",
        "Не удалось зарегистрировать сочетание. Выберите другое в настройках; панель доступна через значок ключа в строке меню.": "Impossible d’enregistrer le raccourci. Choisissez-en un autre dans les réglages. Vous pouvez ouvrir le panneau via l’icône de clé dans la barre des menus.",
        "Аккаунты и настройки…": "Comptes et réglages…",
        "Завершить NotchOTP": "Quitter NotchOTP",
        "Правка": "Édition",
        "Отменить": "Annuler l’action",
        "Вырезать": "Couper",
        "Копировать": "Copier",
        "Вставить": "Coller",
        "Выбрать всё": "Tout sélectionner",
        "Это сочетание занято. Попробуйте другое; прежнее сочетание продолжает работать.": "Ce raccourci est déjà utilisé. Essayez-en un autre. Votre ancien raccourci fonctionne toujours.",
        "Выберите изображение с QR-кодом": "Choisissez une image avec un code QR",
        "Не удалось открыть изображение. Выберите PNG или JPEG с QR-кодом.": "Impossible d’ouvrir l’image. Choisissez un fichier PNG ou JPEG contenant un code QR.",
        "На изображении несколько аккаунтов. Обрежьте его до одного QR-кода.": "L’image contient plusieurs comptes. Recadrez-la pour ne garder qu’un seul code QR.",
        "QR-код TOTP не найден. Выберите более чёткое изображение кода из настроек безопасности сервиса. Пакетный перенос Google не поддерживается.": "Aucun code QR TOTP trouvé. Choisissez une image plus nette dans les réglages de sécurité du service. Le transfert groupé de Google n’est pas pris en charge.",
        "Ваши коды. Под рукой.": "Vos codes. À portée de main.",
        "Вызовите панель, выберите аккаунт и нажмите Enter.": "Ouvrez le panneau, choisissez un compte et appuyez sur Entrée.",
        "Деморежим · показаны тестовые аккаунты": "Mode démo · comptes d’exemple",
        "Аккаунты": "Comptes",
        "Читаем…": "Lecture…",
        "QR из файла": "QR depuis un fichier",
        "Добавить": "Ajouter",
        "Глобальное сочетание": "Raccourci global",
        "Нажмите справа, затем введите новое сочетание.": "Cliquez à droite, puis appuyez sur un nouveau raccourci.",
        "Используйте Control, Option или Command вместе с клавишей. Escape — отмена.": "Utilisez Contrôle, Option ou Commande avec une touche. Échap pour annuler.",
        "Аккаунт": "Compte",
        "Текст": "Saisir",
        "Поиск": "Rechercher",
        "Закрыть": "Fermer",
        "Показать панель": "Afficher le panneau",
        "Ключи хранятся в связке ключей этого Mac. Всё работает локально.": "Les clés sont conservées dans le trousseau de ce Mac. Tout fonctionne localement.",
        "Добавить аккаунт?": "Ajouter le compte ?",
        "Не удалось выполнить действие": "Impossible d’effectuer l’action",
        "Понятно": "OK",
        "Откройте доступ к связке ключей": "Déverrouillez le trousseau",
        "Повторить": "Réessayer",
        "Добавьте первый аккаунт": "Ajoutez votre premier compte",
        "Выберите QR-код из настроек двухфакторной\nаутентификации или введите секретный ключ.": "Choisissez un code QR dans les réglages d’authentification\nà deux facteurs ou saisissez une clé secrète.",
        "Показать": "Afficher",
        "Удалить аккаунт": "Supprimer le compte",
        "Новый аккаунт": "Nouveau compte",
        "Способ": "Méthode",
        "Секретный ключ": "Clé secrète",
        "Ссылка otpauth": "Lien otpauth",
        "Сервис": "Service",
        "Например, GitHub": "Par exemple, GitHub",
        "Например, work или email": "Par exemple, travail ou e-mail",
        "Секретный ключ Base32": "Clé secrète Base32",
        "Ключ из настроек двухфакторной аутентификации": "Clé issue des réglages d’authentification à deux facteurs",
        "Дополнительные параметры": "Réglages avancés",
        "Алгоритм": "Algorithme",
        "Цифры": "Chiffres",
        "Период, секунд": "Période en secondes",
        "Ссылка из настроек сервиса": "Lien issu des réglages du service",
        "Ключ останется в связке ключей этого Mac.": "La clé restera dans le trousseau de ce Mac.",
        "Период должен быть целым числом секунд.": "La période doit être un nombre entier de secondes.",
        "Некорректные параметры кода или системное время.": "Les paramètres du code ou l’heure système sont incorrects.",
        "Этот алгоритм не поддерживается. Используйте SHA1, SHA256 или SHA512.": "Cet algorithme n’est pas pris en charge. Utilisez SHA1, SHA256 ou SHA512.",
        "Связка ключей закрыта": "Trousseau verrouillé",
        "Открыть настройки": "Ouvrir les réglages",
        "Настроить NotchOTP": "Configurer NotchOTP",
        "Скопировано": "Copié",
        "Enter — скопировать · Tab — следующий · Начните печатать для поиска": "Entrée : copier · Tab : suivant · Tapez pour rechercher",
        "Найти аккаунт…": "Rechercher un compte…",
        "Ничего не найдено": "Aucun compte trouvé",
        "↑↓ Выбрать": "↑↓ Choisir",
        "↵ Копировать": "↵ Copier",
        "Язык": "Langue",
        "Как в macOS": "Comme macOS",
        "Применяется сразу, без перезапуска.": "Les changements s’appliquent immédiatement.",
        "Удалить %@?": "Supprimer %@ ?",
        "Удалить %@": "Supprimer %@",
        "Показать код   %@": "Afficher le code   %@",
        "%d цифр · %d сек": "%d chiffres · %d s",
        "%d цифр · %d сек · %@": "%d chiffres · %d s · %@",
        "Осталось %d секунд": "%d secondes restantes",
        "Ошибка %d": "Erreur %d",
        "Связка ключей недоступна: %@. Разблокируйте её и попробуйте снова.": "Le trousseau est indisponible : %@. Déverrouillez-le et réessayez.",
    ]
}
